"""
Email notification service using smtplib.
Used asynchronously via FastAPI BackgroundTasks.
"""

import smtplib
from email.message import EmailMessage
from app.config import settings

def send_attendance_report(student_email: str, student_name: str, semester: int, theory_pct: float, practical_pct: float, fine: int):
    """
    Sends an automated attendance & fine report to the student.
    """
    if not student_email:
        return
        
    if not settings.SMTP_PASSWORD:
        print(f"[Email Service] SMTP Password missing. Skipping email to {student_email}")
        return

    subject = f"Attendance & Fine Report - Semester {semester}"
    
    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <h2>Hello {student_name},</h2>
        <p>Your attendance report for <strong>Semester {semester}</strong> has been finalized by your Class Incharge.</p>
        
        <table style="border-collapse: collapse; width: 100%; max-width: 400px; margin-top: 15px;">
            <tr style="background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                <td style="padding: 10px;"><strong>Theory Attendance</strong></td>
                <td style="padding: 10px; color: {'#059669' if theory_pct >= 75 else '#ef4444'}; font-weight: bold;">{theory_pct}%</td>
            </tr>
            <tr style="border-bottom: 1px solid #e2e8f0;">
                <td style="padding: 10px;"><strong>Practical Attendance</strong></td>
                <td style="padding: 10px; color: {'#059669' if practical_pct >= 75 else '#ef4444'}; font-weight: bold;">{practical_pct}%</td>
            </tr>
            <tr style="background-color: #fff1f2; color: #be123c;">
                <td style="padding: 10px;"><strong>Accumulated Fine</strong></td>
                <td style="padding: 10px; font-weight: bold;">₹ {fine}</td>
            </tr>
        </table>
        
        <p style="margin-top: 20px;">If you have any questions, please contact your Class Incharge or HOD.</p>
        <p style="font-size: 0.85em; color: #888;">This is an automated message generated by the CDH v4 Attendance System.</p>
    </body>
    </html>
    """

    msg = EmailMessage()
    msg['Subject'] = subject
    msg['From'] = settings.SMTP_USERNAME
    msg['To'] = student_email
    msg.set_content("Please enable HTML to view this email.")
    msg.add_alternative(html_content, subtype='html')

    try:
        with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
            server.set_debuglevel(0)
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(msg)
            print(f"[Email Service] Successfully sent report to {student_email}")
    except Exception as e:
        print(f"[Email Service] Failed to send email to {student_email}: {str(e)}")
